---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-pvc
  labels:
    name: bggdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi