apiVersion: v1
kind: Secret
metadata:
  name: wpdb-secret
  labels:
    name: wpdb-secret
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=
  DATABASE: d3BkYg==
  USER: d3BkYg==
  PASSWORD: Y2hhbmdlaXQ=