---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: wpdb-cluster
  labels:
    name: wpdb-cluster
    app: wpdb
    tier: database
spec:
  replicas: 1
  secretName: wpdb-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: wpdb-database
  labels:
    name: wpdb-database
    app: wpdb
    tier: database
spec:
  database: wpdb-database
  clusterRef:
    name: wpdb-cluster