---
apiVersion: v1
kind: Service
metadata:
  name: wpdb-svc
  labels:
    name: wpdb-svc
spec:
  type: ClusterIP
  selector:
    name: wpdb-pod
    app: wpdb
    tier: database
  ports:
    - protocol: TCP
      targetPort: 3306
      port: 3306