apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-backend-svc
  name: default-backend-svc
spec:
  selector:
    app: default-backend-pod
  type: ClusterIP
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
