apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../app/base
- ../db/base

namespace: wpns-client1
commonLabels:
  client: client1

patchesJson6902:
- path: patch.yml
  target:
    kind: Ingress
    name: wpapp-ing
    version: v1
    group: networking.k8s.io
