---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  labels:
    name: nwdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi