---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-pod
    app: bggdb
    tier: database
  ports:
    - protocol: TCP
      targetPort: 3306
      port: 3306