---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: NodePort
  selector:
    name: bggapp-pod
    app: bggapp
    tier: backend
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 8080