---
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  labels:
    name: docker-secret
type: kubernetes.io/dockerconfig.json
data:
  .dockerconfigjson: (cat ~/.docker/config.json | base64 | tr -d '\n')