---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: LoadBalancer
  selector:
    name: dov-pod
    app: dov
    tier: backend
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 8080